mill1000/midea-msmart

msmart/base_command.py
msmart/device/AC/appliance.py
msmart/device/AC/command.py
msmart/device/AC/test_command.py

This PR allows a response through if either a CRC or checksum matches. Some devices appear to protect the response payload with a 2nd checksum instead of a CRC8. See issue #9 for related reports.
Additionally this PR
* Add some unit tests for response parsing
* Fixes an uncaught exception when trying to access the response ID field after failing to parse
* Fixes some lint issues with the response classes
* Restructures the response parsing.
Close #9  and close mill1000/midea-ac-py#11

Accept valid checksum or CRC for device responses

---

msmart/cloud.py

The API recently started requiring a deviceID in the request. Close #16, and close mac-zhou/midea-ac-py#217

Add missing deviceID to API requests.

---

msmart/cloud.py

Test cases started to fail with a fixed device ID. Maybe the Cloud was blocking logins due to multiple devices claiming to be a single device.
Possible fix for #38

Use random device ID and increase timeout in Cloud API requests

---

msmart/base_device.py
msmart/discover.py

During discovery it is expected (for reasons) that some authentication attempts may fail. Currently this causes an error message to be emitted.
This PR adds a (hacky) option to silence log reports from the device's `authenticate` method. Close mill1000/midea-ac-py/issues/23

Supress logger messages of failed authentications during discovery

---

msmart/discover.py

Fixes an uncaught exception if a user has an unsupported device during discovery. Currently the an instance of the base device class is created which does not support refresh() or update() methods.
This should let us more gracefully fail discovery when unsupported devices are present. The logger will report an error and HA users will get a message about being unable to connect.

Catch NotImplementedError when connecting to device during discovery

---

msmart/lan.py

Add a timeout to LAN modules `_connect` calls. The current timeout is approximately 2 minutes which must be OS dependent. This implements a significantly shorter timeout of 5 seconds.

Add a timeout to LAN connect calls

---

msmart/device/AC/device.py
msmart/device/AC/test_device.py

Ensure IntEnumHelper `get_from_value` and `get_from_name` return the proper enum classes when using default values.
Add test cases to ensure this works as expected.
Reported in mill1000/midea-ac-py/issues/32

Fix device enum fallback behavior which was not returning enum class instances

---

msmart/base_device.py
msmart/lan.py

Add hooks to Device and LAN classes to enable specifying a maximum connection lifetime. Device connections will automatically be re-established whenever a connection is older than this limit.
Hopefully address https://github.com/mill1000/midea-ac-py/issues/30

Add ability to limit maximum connection lifetime

---

msmart/device/AC/command.py
msmart/device/AC/test_command.py

This add support for temperatures below 17 degrees celsius. Based on https://github.com/dudanov/MideaUART/commit/3bbd505ee58792a620ad115f9f26652b688f58e3. Tested using Midea Mission Pro 9 - both retrieving the current target temperature and setting target temperature to 16.0 or 16.5 (16 is the lowest supported by the device).

Support for target temperature below 17 degrees celsius

---

msmart/device/AC/command.py
msmart/device/AC/test_command.py

Improve reported temperature precision

---

msmart/discover.py

Reported in https://github.com/mill1000/midea-ac-py/issues/48
A user has devices that report a different IP than the packet is received on. This PR switches the discovered IP from the reported to the actual IP.

Use actual IP instead of reported IP address when discovering devices

---

msmart/device/AC/command.py
msmart/device/AC/test_command.py

Report a default set of fan supported speeds (Low, Medium, High, Auto) when no specific fan speed capability is received.
Close #88

Fix supported fan speeds when no fan speed capability is received

---

Dockerfile

Alpine 3.19 switched to a externally managed pip environment which makes package installation difficult.
Originally attempted to resolve this with pipx in #101, but the builds failed on ARM targets as the pycryptodome dependency needs to be built from source.

Pin Alpine version in Dockerfile to 3.18

---

pyproject.toml

Setuptools was complaining about an ambiguous configuration because the submodule in msmart were not explicitly included in the packages option.
As a side note, I find it odd that's it's so particularly difficult to tell setuptools to only package a single folder.

Fix warnings from setuptools when packaging project

---

msmart/device/AC/device.py

Close #95, and also https://github.com/mill1000/midea-ac-py/issues/67
Waiting on confirmation from another user that their system uses 80 (0x50) as a high fan speed

Change HIGH fan speed value to 80

---

msmart/base_device.py
msmart/cli.py
msmart/discover.py

Throw on authentication failures so the callers can handle failures intelligently based on their needs.
This is a somewhat **breaking** change! Previous implementation merely logged the failure and returned a boolean to indicate success. User of the library should put authentication calls in a `try...except` and handle failures gracefully.

Throw exceptions on authentication failures

---

msmart/device/AC/device.py
msmart/device/AC/test_command.py
msmart/device/AC/test_device.py

When parsing PropertiesResponses, only update the device state with fields from the message that are not None.
This should fix repeated logs of 
```
Unknown <enum 'SwingAngle'>: None
```
which were originally noticed in https://github.com/mill1000/midea-ac-py/issues/101#issuecomment-1999156216

Only update swing angles when response field is not none

---

msmart/device/AC/command.py
msmart/device/AC/device.py
msmart/device/AC/test_command.py
msmart/device/AC/test_device.py

Original attempt in #114 had some shortcomings due to the adhoc nature of responses. It was possible for a PropertiesResponse to appear to be received in response from another command which caused the CRC to fail.
This approach is a little more of a hammer. It simply ignores the CRC on all PropertiesResponse.

Accept PropertiesResponses with invalid CRCs. Redo of #114

---

msmart/device/AC/command.py
msmart/device/AC/test_command.py

Close #122 
Add test case to ensure 0xB5 responses with different frame types are ignored.

Ignore "capability" responses with unexpected frame type.

---

msmart/device/AC/command.py
msmart/device/AC/test_command.py

When testing Anion supports, some other warnings were generated in the logs about an unsupported property
```
2024-05-07 00:28:46.302 WARNING (MainThread) [msmart.device.AC.command] Unsupported property. ID: 0x001A, Size: 1.
``` 
This is due to #120, in which the Buzzer property was inserted into every Properties command. However, a parser was never defined for the response.
We don't really care about the response, so define a parser that returns None and don't store it.

Fix unsupported property warnings for Buzzer ID in logs

---

msmart/device/AC/command.py
msmart/device/AC/device.py
msmart/device/AC/test_command.py
msmart/device/AC/test_device.py

The current Anion implementation is broken (#124, https://github.com/mill1000/midea-ac-py/issues/131, https://github.com/mill1000/midea-ac-py/issues/128).
While #126 is being worked on and debugged, this reverts the current implementation.

Revert broken Anion implementation

---

msmart/device/AC/command.py
msmart/device/AC/device.py
msmart/device/AC/test_command.py

Close #124 and hopefully https://github.com/mill1000/midea-ac-py/issues/128
Upon further review of the Lua and plugin, it appears the `anion` property is never used. Instead it controls a `purifier` setting in the standard protocol.
Additional testing will be necessary.

Replace Anion property with standard protocol purifier

---

msmart/device/AC/device.py
msmart/device/AC/test_device.py

Fix condition in _update_state which caused zero valued property values to not update the device state.
Update testcases to ensure this is tested.
Should fix https://github.com/mill1000/midea-ac-py/issues/122

Fix conditionals for swing angle properties

---

msmart/cloud.py
msmart/lan.py

Instead use `datetime.now(timezone.utc)` which is timezone aware.

Replace deprecated `datetime.utcnow()`

---

.github/workflows/prune-ghcr.yml

Disable pruning of untagged images to prevent breaking multi-arch images until a better solution is found.
https://github.com/snok/container-retention-policy/issues/63
https://github.com/vlaurin/action-ghcr-prune/issues/76

Disable pruning of untagged Docker images

---

README.md
msmart/cli.py

Add new `control` command to the CLI which enables setting device properties.
Basic syntax is as follows:
```
msmart-ng control DEVICE_IP setting1=value1 setting2=value2
```
The CLI will attempt to convert the incoming values to the correct types. 
- Enum types can use the number and/or the name. 
- Booleans can be written as true/false or True/False
Example
```
msmart-ng control DEVICE_IP power_state=True fan_speed=20 target_temperature=25 operational_mode=heat display_on=True
```
Close #96

Add control capability to CLI

---

.dockerignore

Currently the Docker images don't have msmart-ng versions that match their tag.
```
docker run --network=host ghcr.io/mill1000/msmart-ng:2024.7.0 -v
msmart version: 2024.7.1.dev0+gab34eb4.d20240710
```
Update dockerignore to ensure `git status` is clean when building Docker images, to ensure the built version matches the tag.

Fix tagged docker images reporting different version than tag

---

msmart/device/AC/device.py

Expose `supports_humidity` via a property so the HA integration can intelligently decide to create a humidity sensor

Expose supports_humidity property

---

msmart/device/AC/device.py

Some users have raised issues that "high" is not 100. The "high" fan speed was reduced to 80 in #104.
https://github.com/mill1000/midea-ac-py/issues/143
https://github.com/mill1000/midea-ac-py/issues/96
As a comprise, this PR adds a new fan speed "Max" but it's only made available when custom speeds are supported.

Add a MAX fan speed when custom speeds are supported

---

msmart/device/AC/device.py

Some users have devices that don't respond to humidity messages causing the device to appear offline when refresh() is called.
https://github.com/mill1000/midea-ac-py/issues/188

Default humidity support to False

---

msmart/base_device.py
msmart/device/AC/device.py
msmart/lan.py

Add additional peer information to certain log statements.  This should ease debugging when multiple devices are present.

Add peer information to more logs

---

msmart/device/AC/device.py

Capabilities should always be known even if they're not accurate.

Remove Optional type hint on "supports" properties.

---

msmart/device/AC/command.py
msmart/device/AC/device.py
msmart/device/AC/test_command.py
msmart/device/AC/test_device.py

It appears devices want a value of 0x01 to disable breeze modes, even though they return a value of 0 to indicate it's off.
Add checks for execution errors in properties responses.
Add/modify test cases for these execution errors
Close #161

Fix inability to turn off breeze modes

---

msmart/device/AC/device.py

Tidy up "breeze" mode implementation using an enum to make the interaction between breeze away, breeze mild and breezeless more seamless

Use enum for "breeze" mode

---

msmart/device/AC/command.py
msmart/device/AC/device.py
msmart/device/AC/test_command.py
msmart/device/AC/test_device.py

- Relocate property encoding from device.py to command.py
- Replace property parsers with decode() method
- Add testcases to verify property encoding/decoding

Refactor property decode/encode

---

msmart/device/AC/command.py
msmart/device/AC/device.py
msmart/device/AC/test_command.py
msmart/device/AC/test_device.py

Parse energy data as both BCD and binary.
Add an option to the device class to switch between the 2.
Close #154

Add alternate energy/power response parsing

---

.github/workflows/publish-pypi.yml

https://blog.pypi.org/posts/2024-11-14-pypi-now-supports-digital-attestations/

Use trusted publishing with PyPi and generate digital attestations

---

msmart/device/AC/command.py
msmart/device/AC/test_command.py
msmart/device/AC/test_device.py

Close #174 
When merged, this PR will need to be reverted before upgrading the msmart version https://github.com/mill1000/midea-ac-py/pull/248

Scale binary energy values by an additional factor of 10

---

msmart/cli.py
msmart/cloud.py
msmart/const.py
msmart/discover.py
msmart/tests/test_cloud.py

It appears the server are region locking accounts. This PR adds support for specifying a region which is used solely for selecting different built-in credentials. Close #176

Add support for additional cloud credentials based on region

---

msmart/device/AC/command.py
msmart/device/AC/test_command.py
msmart/device/AC/test_device.py

Reverts mill1000/midea-msmart#180
Another user reported (https://github.com/mill1000/midea-ac-py/issues/276) that scaling by another factor of 10 is not correct for all devices.
Instead we'll keep the original scaling, and have midea-ac-py perform the scaling

Revert "Scale binary energy values by an additional factor of 10"

---

msmart/device/AC/command.py
msmart/device/AC/device.py

When debugging midea-ac-py, users often have multiple devices which can make it difficult to associate certain log reports with specific devices.
This PR adds the device ID to most the warnings and response payload messages.

Add device ID to log messages to improve debugging multuiple devicest at once

---

msmart/device/AC/command.py
msmart/device/AC/device.py
msmart/device/AC/test_command.py
msmart/device/AC/test_device.py

Add support for auxiliary/electric heat when supported by the device. From what I can gather there are 2 operating modes for aux heat. 
* Regular mode -> Electric heater is used as needed
* Forced mode ("independent" aux heat) -> Only use electric heater

Add support auxilary/electric/emergency heat

---

msmart/base_device.py
msmart/device/AC/device.py
msmart/device/AC/test_device.py
msmart/tests/test_device.py

Update command/response handling to keep device online if at least 1 response is received during a refresh.
As a side effect, only calls to refresh() will update the device online state.
Close #186

Keep device online of any command received a response

---

msmart/cli.py
pyproject.toml

Project has been around long enough that users should be familiar with the new cli `msmart-ng`

Remove legacy CLI

---

msmart/cloud.py
msmart/discover.py

Allowing CloudErrors to propagate up will allow better error reporting for users of HA

Update discovery flow to throw exceptions when cloud connection fails

---

msmart/device/AC/command.py
msmart/device/AC/test_command.py

The reported temperature was wrong - decimal part never went ove 0.4.
Im not sure if this is general issue for more devices, or its just me, but I managed to find the culprit in for my Midea AC.
The temperature in payload is rounded to 0.5, but the fraction part is set to full range 0.0-0.9.  When adding it up, it results in incorrect values: 25.5+0.9 = 26.4 instead of 25.9 and in fact it never reaches values 25.5 - 25.9
I need to round the intergral part of temperature to 0.0 to get the correct result.
payload from my AC:
`c001ae647f7f00000000006541120099000000000000000100000000a9`

Fixed calculation of temperature with decimals

---

pyproject.toml

Should resolve the following warnings in builds
```
#29 3.637 /tmp/build-env-wq4qrbw7/lib/python3.12/site-packages/setuptools/config/_apply_pyprojecttoml.py:82: SetuptoolsDeprecationWarning: `project.license` as a TOML table is deprecated
#29 3.637 !!
#29 3.637 
#29 3.637         ********************************************************************************
#29 3.637         Please use a simple string containing a SPDX expression for `project.license`. You can also use `project.license-files`. (Both options available on setuptools>=77.0.0).
#29 3.637 
#29 3.637         By 2026-Feb-18, you need to update your project and remove deprecated calls
#29 3.637         or your builds will no longer be supported.
#29 3.637 
#29 3.637         See …
```

Update pyproject licensing to be compliant with PEP 639

---

msmart/device/AC/test_device.py

Forgot to rename a reference from LOWER to DOWN

Fix bad Cascade unit test

---

msmart/tests/test_cloud.py

These unit tests often fail due to timeouts or the Cloud rejecting them.

Skip Cloud tests when running on CI

---

msmart/device/AC/device.py
msmart/device/AC/test_device.py

It appears a user is getting back responses with IDs that match capabilities responses by the response is constructed as a base Response object.
This is likely due to #123 
However it's causing occasion errors for users when we try to access the non-existent `raw_capabilities` attribute.
https://github.com/mill1000/midea-ac-py/issues/358#issuecomment-3171895494

Use class instead of ID to filter for specific responses

---

msmart/device/AC/device.py
msmart/device/AC/test_device.py
msmart/utils.py

Add methods to fetch total energy, current energy and real time power in either data format.
Deprecate existing properties and the `use_alternative_energy_format` property.

Add support for accessing individual energy data fields in either format

---

msmart/device/AC/test_command.py
msmart/frame.py

Add a length check to received frames before checking the checksum. The user in #234 has devices that are returning bogus responses which pass checksums (all 0s) but throw index errors since they are too short.

Validate frame length

---

msmart/device/AC/device.py
msmart/device/AC/test_device.py

Update send_command_get_response so device can be marked as online, but unsupported.
This is an attempt to allow midea-ac-py to differential between a valid connection to a device, but an unsupported one.
With this change
* A device is marked online as long as it receives any response
* A device is marked as supported if it received any valid response at least once. The supported state is sticky, once set it will remain True.

Update device online/supported logic 
