msmart/device/AC/appliance.py, msmart/device/AC/command.py
Replace and close #4, taken from https://github.com/mac-zhou/midea-msmart/pull/100
=> Fix missing temperatures

msmart/device/AC/appliance.py, msmart/device/AC/command.py
Expose sleep mode to allow mill1000/midea-ac-py/pull/4 to use the sleep mode preset. Close #3
=> Expose sleep mode

.github/workflows/autopep8.yml
Add autopep8 workflow to check formatting
=> Add workflow to check formatting

msmart/device/AC/command.py
Fixed an issue where cool_mode was incorrectly detected as unsupported
=> Fix incorrect cool_mode capability detection

msmart/tests/test_cloud.py, msmart/tests/test_discover.py
Also restructured the test files into a tests subdir
=> Add discover module testcases

.github/workflows/checks.yml, msmart/__init__.py, pyproject.toml
Update actions to run on unittests on 3.8->3.11
=> Set minimum Python version to 3.8.

msmart/device/AC/appliance.py
This is a breaking change as supported_operation_modes and supported_swing_modes now return lists of the raw enum type instead of strings
=> Update enum classes and handling in AC device.

msmart/base_device.py, msmart/device/AC/device.py, msmart/discover.py
Requires mill1000/midea-ac-py/pull/18
=> Updates to support HA config flow discovery

msmart/cloud.py, msmart/discover.py, msmart/tests/test_cloud.py
Add test cases for these exceptions and finish up type hints
=> Update cloud module to throw exceptions

msmart/device/AC/test_command.py
=> Add capabilities test cases.

msmart/base_command.py, msmart/base_device.py, msmart/cli.py, msmart/crc8.py, msmart/device/AC/command.py, msmart/device/AC/device.py, msmart/device/AC/test_command.py, msmart/discover.py, msmart/lan.py, msmart/tests/test_discover.py, msmart/tests/test_lan.py, msmart/types.py
Add type hints across the project and address all discovered issues.
=> Implement additional type hint and fix discovered issues

msmart/device/AC/command.py, msmart/device/AC/test_command.py
Define some additional test cases to test specific capabilities parsers
=> Define some additional capabilties test cases

.github/workflows/checks.yml
Some adjustments to checks workflow.
1. Cancel duplicate workflows
2. Run unit tests in parallel, hoping latest cloud changes will allow us to run this faster
3. Format the YAML
=> Update checks workflow

.github/workflows/publish-pypi.yml
=> Add workflow to publish releases to PyPi

msmart/device/AC/device.py
and reorg existing supports_* properties closer to related setters/getters
=> Add supports_display_control property

.github/workflows/prune-ghcr.yml
1. On PR closing, remove associated images
2. Weekly, remove untagged images
=> Add workflow to prune GHCR images.

msmart/base_device.py, msmart/device/AC/device.py
Fix some misc organization issues with the device classes
=> Device class cleanup

msmart/lan.py
Fix some issues found in the LAN class while looking at user's logs
Close #63 and close #62
=> Address some LAN issues

msmart/base_command.py, msmart/device/AC/command.py, msmart/device/AC/device.py
Finally opened the AC.zip, lo-and-behold it contains some lousy reference code.
Anyway, realized I can use the beep bit in the toggle display command too.
Close #52
=> Fix sound on toggle_display

Dockerfile, README.md, msmart/base_device.py, msmart/cli.py, msmart/device/AC/device.py, pyproject.toml
=> Implement a new CLI with support for querying device state and capabilities

msmart/const.py
Old account appears to have become invalid
=> Update cloud account credentials

msmart/cli.py, msmart/device/AC/command.py, msmart/device/AC/device.py, msmart/device/AC/test_command.py
Using the available reference code update the capability parser with new IDs, fixed parsers, & better names.
Add fan speed capability parsing, and expose filter reminder capability
Close #79, and close #83 and close #84
=> Update capabilities from reference code

msmart/device/AC/device.py
It wasn't exposed anyway, and I feel the application level should deal with that logic anyway
=> Remove keep_last_known_online_state functionality.

msmart/device/AC/command.py, msmart/device/AC/device.py, msmart/device/AC/test_command.py
=> Implement additional capabilities request

msmart/device/AC/command.py, msmart/device/AC/test_command.py
* Add capability readers for swing UD and LR angle.
* Remove invalid INDOOR_HUMIDITY capability ID
* Replace inaccurate get_bool parsers
=> Update capabilities parsing

.github/workflows/checks.yml, pyproject.toml
=> Add Python 3.12 to workflows and pyproject

msmart/device/AC/command.py, msmart/device/AC/device.py, msmart/device/AC/test_command.py, msmart/device/AC/test_device.py, msmart/utils.py
Begin implementing the "new" protocol set to enable controlling some advanced features. I've taken to calling this the "properties" protocol.
Close #97 and in support of https://github.com/mill1000/midea-ac-py/issues/69, https://github.com/mill1000/midea-ac-py/issues/60 & https://github.com/mill1000/midea-ac-py/issues/31
=> Implement "new" properties protocol

msmart/device/AC/command.py, msmart/device/AC/device.py
Hopefully this makes SetProperties commands respect the beep setting and close #119
=> Send the buzzer property in all SetProperties commands

msmart/device/AC/command.py, msmart/device/AC/device.py, msmart/device/AC/test_command.py, msmart/device/AC/test_device.py
In support of https://github.com/mill1000/midea-ac-py/issues/120
=> Add support for anion (ionizer)

.devcontainer/devcontainer.json, Dockerfile
Switch to Python 3.12 and Alpine 3.20
=> Update Dockerfile and devcontainer

msmart/device/AC/command.py, msmart/device/AC/device.py, msmart/device/AC/test_command.py, msmart/device/AC/test_device.py
Add support for requesting indoor humidity, and power usage if devices claim support.
Add support for setting target humidity.
Close #12 and close #105 and provide necessary support for https://github.com/mill1000/midea-ac-py/issues/5 and https://github.com/mill1000/midea-ac-py/issues/86
=> Add support for humidity set point and power usage

msmart/device/AC/command.py, msmart/device/AC/test_command.py
This warning comes up every now and then in user logs. Totally harmless but I think it does cause some distress to new users.
https://github.com/mill1000/midea-ac-py/issues/81
=> Supress warning from unknown and unsupported capabilities

msmart/device/AC/command.py, msmart/device/AC/device.py
Add SMART_DRY operational mode and expose properties for checking target humidity support
=> Add support for custom dry

msmart/device/AC/command.py, msmart/device/AC/device.py
Close #147, in support of https://github.com/mill1000/midea-ac-py/pull/180
In need of testers.
=> Add active/self clean support

.github/workflows/prune-ghcr.yml
This action should support multi-arch images
=> Use ghcr-cleanup-action to prune untagged images

msmart/device/AC/command.py, msmart/device/AC/device.py, msmart/device/AC/test_command.py
Add "rate select" functionality. Also known as Gear, Gear5 or Gen Mode.
Close #148
=> Add "rate select" functionality

msmart/device/AC/command.py, msmart/device/AC/device.py, msmart/device/AC/test_command.py, msmart/device/AC/test_device.py
Adds support for various "breeze" modes like
* Breezeless/Silky Cool
* Breeze Mild
* Breeze Away
Close #150 and supports https://github.com/mill1000/midea-ac-py/issues/186
=> Add support for "breeze" modes

msmart/cloud.py, msmart/tests/test_cloud.py
Catch additional exceptions from httpx during cloud requests.
=> Catch request exceptions from httpx

msmart/device/AC/command.py, msmart/device/AC/test_command.py, msmart/device/AC/test_device.py
Tidy up some capability processing and add device level test cases for capabilities.
Specifically we want to test the more complex device-level capabilities like 
* Breeze Control
* Rate Select
* Smart Dry
=> Add device-level capabilities tests

msmart/lan.py, msmart/tests/test_lan.py
=> Resolve occasional exceptions in user logs by catching CancelledError

msmart/device/AC/command.py, msmart/device/AC/device.py
Work in progress.
Add IECO support. 
Close #156
=> Add IECO support

msmart/base_device.py, msmart/cloud.py, msmart/device/AC/command.py, msmart/device/AC/device.py, msmart/discover.py, msmart/lan.py, msmart/utils.py, pyproject.toml
Python 3.8 is EOL
Removing EOL versions allows us to use more modern language features and typing.
=> Update minimum supported Python version to 3.9

msmart/device/AC/device.py, msmart/device/AC/test_device.py
Update test cases to check each enum
=> Add missing DEFAULT value for AuxHeat enum

msmart/device/AC/command.py
Original report here: https://github.com/mill1000/midea-ac-py/issues/310
=> Fix unconditionally set independent aux heat bit

msmart/cloud.py, msmart/discover.py
Adds the hooks to fix [midea-ac-py issue #311](https://github.com/mill1000/midea-ac-py/issues/311)
=> Add ability to override method for getting an httpx AsyncClient

msmart/cli.py, msmart/cloud.py, msmart/const.py, msmart/discover.py, msmart/tests/test_cloud.py
Close #193 and https://github.com/mill1000/midea-ac-py/issues/322
=> Switch to NetHome Plus cloud to restore get_token and discovery functionality

msmart/cli.py
=> Remove references to china cloud in CLI

msmart/device/AC/command.py
=> Downgrade "Unknown capability ID" message to INFO

msmart/tests/test_discover.py
Add additional testcases for Discover which test the entire flow using proper mocks and patches.
Close #202
=> Add additional Discover flow tests

msmart/device/AC/command.py, msmart/device/AC/device.py, msmart/device/AC/test_command.py, msmart/device/AC/test_device.py
Requested here: https://github.com/mill1000/midea-ac-py/issues/359
Still untested, needs tests with real device data too
=> Add support for Cascade function

msmart/cli.py
=> Add option to CLI to request energy information

msmart/device/AC/device.py
=> Remove use of deprecated properties in to_dict

msmart/device/AC/command.py, msmart/device/AC/device.py, msmart/device/AC/test_command.py
=> Extract and expose error code from StateResponse
